drop database if exists auctionmark;
drop database if exists epinions;
drop database if exists jpab;
drop database if exists linkbench;
drop database if exists resourcestresser;
drop database if exists seats;
drop database if exists sibench;
drop database if exists smallbank;
drop database if exists tatp;
drop database if exists tpcc;
drop database if exists twitter;
drop database if exists voter;
drop database if exists wikipedia;
drop database if exists ycsb;

create database auctionmark;
create database epinions;
create database jpab;
create database linkbench;
create database resourcestresser;
create database seats;
create database sibench;
create database smallbank;
create database tatp;
create database tpcc;
create database twitter;
create database voter;
create database wikipedia;
create database ycsb;
